module.exports = {
  testEnvironment: 'jsdom',
  testEnvironmentOptions: {
    customExportConditions: ['node', 'require'],
  },
  testMatch: ['**/*.test.[jt]s?(x)'],
  testPathIgnorePatterns: [
    '/node_modules/',
    'packages/stl-native/',
    // Stubbed components — re-enable as each is rebuilt
    'packages/components/Accordion/',
    'packages/components/AlertDialog/',
    'packages/components/Breadcrumb/',
    'packages/components/Calendar/',
    'packages/components/Carousel/',
    'packages/components/Chart/',
    // 'packages/components/Checkbox/', // re-enabled
    'packages/components/Collapsible/',
    'packages/components/Combobox/',
    'packages/components/Command/',
    'packages/components/ContextMenu/',
    'packages/components/DataTable/',
    'packages/components/DatePicker/',
    'packages/components/Dialog/',
    'packages/components/Drawer/',
    'packages/components/DropdownMenu/',
    'packages/components/Field/',
    'packages/components/Form/',
    'packages/components/HoverCard/',
    'packages/components/InputGroup/',
    'packages/components/InputOTP/',
    'packages/components/Menu/',
    'packages/components/Menubar/',
    'packages/components/NavigationMenu/',
    'packages/components/Pagination/',
    'packages/components/Popover/',
    'packages/components/Resizable/',
    'packages/components/ScrollArea/',
    'packages/components/Select/',
    'packages/components/Sheet/',
    'packages/components/Sidebar/',
    // 'packages/components/Slider/', // re-enabled
    'packages/components/Table/',
    'packages/components/Tabs/',
    'packages/components/Toast/',
    // 'packages/components/Toggle/', // re-enabled
    'packages/components/Tooltip/',
  ],
  collectCoverageFrom: [
    'src/**/*.{ts,tsx}',
    '!src/**/*.d.ts',
    '!src/**/index.{ts,tsx}',
    '!src/__test-utils__/**',
  ],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'mjs', 'cjs'],
  moduleNameMapper: {
    '^@vlting/ui$': '<rootDir>/src/index.ts',
    '^@vlting/ui/(.*)$': '<rootDir>/src/$1',
    '^@vlting/stl$': '<rootDir>/packages/stl/src/index.ts',
    '^@vlting/stl/(.*)$': '<rootDir>/packages/stl/src/$1',
    '^@vanilla-extract/css$': '<rootDir>/src/__test-utils__/mocks/vanilla-extract-css.js',
    '^react-native-svg$': '<rootDir>/src/__test-utils__/mocks/react-native-svg.js',
    '^react-native-svg/(.*)$': '<rootDir>/src/__test-utils__/mocks/react-native-svg.js',
    '^react-native$': '<rootDir>/src/__test-utils__/mocks/react-native.js',
  },
  transform: {
    '^.+\\.(js|jsx|ts|tsx|mjs|cjs)$': ['babel-jest', { configFile: './babel.config.js' }],
  },
  setupFilesAfterEnv: ['./jest.setup.js'],
  transformIgnorePatterns: [
    'node_modules/(?!(react-native|@react-native|react-native-web|@tiptap|invariant|scheduler|@react-aria)/)',
  ],
}
