import { createStub } from '../_stub'

export const H1 = createStub('H1', 'h1')
export const H2 = createStub('H2', 'h2')
export const H3 = createStub('H3', 'h3')
export const H4 = createStub('H4', 'h4')
export const H5 = createStub('H5', 'h5')
export const H6 = createStub('H6', 'h6')
export const P = createStub('P', 'p')
export const Lead = createStub('Lead', 'p')
export const Large = createStub('Large', 'div')
export const Small = createStub('Small', 'small')
export const Muted = createStub('Muted', 'p')
export const Blockquote = createStub('Blockquote', 'blockquote')
export const InlineCode = createStub('InlineCode', 'code')
export const List = createStub('List', 'ul')
export const ListItem = createStub('ListItem', 'li')
