import {
  type ColorNumberKey,
  type ColorPalette,
  CoreColorName,
  DEFAULT_SOURCE_COLORS,
  type ScaleColorName,
} from '../../shared/models/colorGen.models'
import { generateThemeColors, getTextColor } from '../../shared/utils/colorGen.utils'
import { type CharHash, addPrefix } from '../utils'
import type {
  ColorPaletteEntry,
  CssAliasMap,
  CssValueMap,
  ScaleEntry,
  ThemeScale,
} from './scales.models'
import {
  getCssMapFromVars,
  getPropsFromCssMap,
  getThemePropsFromCssMap,
} from './scales.utils'

/** Generator function for `color` theme scale */
export function getColor(hash: CharHash) {
  const cssAliasMap = {} as CssAliasMap<any>
  const cssValueMapFromAliases = {} as CssValueMap

  const addAlias = (k: string, v: string) => {
    cssAliasMap[addPrefix(k)] = addPrefix(v)
    cssValueMapFromAliases[k] = k
  }

  const lightPalette = generateThemeColors<ScaleEntry>(
    DEFAULT_SOURCE_COLORS,
    'light',
    (
      key: keyof ColorPaletteEntry,
      palette: ColorPalette<ScaleEntry>,
      value: string | number,
      numberKey?: ColorNumberKey,
      isMapped = false,
    ) => {
      if (isMapped) {
        addAlias(key, String(value))
      } else {
        palette[key] = { ...hash.var, value: String(value) }
      }
      // Create a matching text alias
      const baseKey = key.replace(String(numberKey), '')
      addAlias(
        `${baseKey}Text${numberKey ?? ''}`,
        getTextColor(baseKey as ScaleColorName, numberKey),
      )
    },
  )

  const shadowBase = { ...hash.var, value: '0 0% 0%' }

  const lightScale = {
    shadowBase,
    shadowBlack: { ...hash.var, value: 'hsl(0 0% 0%)' },
    defaultBody: {
      ...hash.var,
      value: lightPalette[getTextColor(CoreColorName.neutral, 2)].ref,
    },
    defaultHeading: { ...hash.var, value: lightPalette.neutral10.ref },
    // Unique to light palette
    panel: { ...hash.var, value: lightPalette.min.ref },
    shadowLight: { ...hash.var, value: `hsl(${shadowBase.ref} / .05)` },
    shadowHeavy: { ...hash.var, value: `hsl(${shadowBase.ref} / .15)` },
    shadowHeaviest: { ...hash.var, value: `hsl(${shadowBase.ref} / .25)` },
    // Static color constants
    white: { ...hash.var, value: 'hsl(0,0%,100%)' },
    black: { ...hash.var, value: 'hsl(0,0%,0%)' },
    transparent: { ...hash.var, value: 'transparent' },
    shadowColor: { ...hash.var, value: `hsl(${shadowBase.ref} / .15)` },
    // Surface levels (background palette)
    surface1: { ...hash.var, value: lightPalette.min.ref },
    surface2: { ...hash.var, value: lightPalette.background1.ref },
    surface3: { ...hash.var, value: lightPalette.background2.ref },
    inverse: { ...hash.var, value: lightPalette.neutral12.ref },
    ...lightPalette,
  } as const

  const darkVars = {
    shadowBase,
    shadowBlack: lightScale.shadowBlack,
    defaultBody: lightScale.defaultBody,
    defaultHeading: lightScale.defaultHeading,
    // Unique to dark palette
    panel: { ...lightScale.panel, value: lightScale.background3.ref },
    shadowLight: { ...lightScale.shadowLight, value: `hsl(${shadowBase.ref} / .2)` },
    shadowHeavy: { ...lightScale.shadowHeavy, value: `hsl(${shadowBase.ref} / .35)` },
    shadowHeaviest: {
      ...lightScale.shadowHeaviest,
      value: `hsl(${shadowBase.ref} / .5)`,
    },
    // Static color constants (same in dark mode)
    white: lightScale.white,
    black: lightScale.black,
    transparent: lightScale.transparent,
    shadowColor: { ...lightScale.shadowColor, value: `hsl(${shadowBase.ref} / .40)` },
    // Surface levels (dark mode — background palette)
    surface1: { ...lightScale.surface1, value: lightScale.background2.ref },
    surface2: { ...lightScale.surface2, value: lightScale.background1.ref },
    surface3: { ...lightScale.surface3, value: lightScale.min.ref },
    inverse: { ...lightScale.inverse, value: lightScale.max.ref },
    ...generateThemeColors<ScaleEntry>(
      DEFAULT_SOURCE_COLORS,
      'dark',
      (
        key: keyof ColorPaletteEntry,
        palette: ColorPalette<ScaleEntry>,
        value: string | number,
        _numberKey?: ColorNumberKey,
        isMapped = false,
      ) => {
        if (!isMapped) {
          palette[key] = { ...lightScale[key], value: String(value) }
        }
      },
    ),
  } as const

  ////////////////////////////////////////////////////////////////////////////////
  const vars = lightScale
  const cssValueMap = {
    ...getCssMapFromVars(lightScale),
    ...cssValueMapFromAliases,
  } as const
  const themeProps = { ...getThemePropsFromCssMap(cssValueMap) } as const

  return {
    vars,
    darkVars,
    themeProps,
    cssValueMap,
    cssValueMapProps: getPropsFromCssMap(cssValueMap),
    cssAliasMap,
  } as ThemeScale<typeof vars, typeof themeProps, typeof cssValueMap, typeof cssAliasMap>
}

// FILTER KEYS ////////////////////////////////////////////////////////////////
// Used for generating types that map to only parts of this scale

export const colorCore = {
  min: true,
  max: true,
  primary1: true,
  primary2: true,
  primary3: true,
  primary4: true,
  primary5: true,
  primary6: true,
  primary7: true,
  primary8: true,
  primary9: true,
  primary10: true,
  primary11: true,
  primary12: true,
  secondary1: true,
  secondary2: true,
  secondary3: true,
  secondary4: true,
  secondary5: true,
  secondary6: true,
  secondary7: true,
  secondary8: true,
  secondary9: true,
  secondary10: true,
  secondary11: true,
  secondary12: true,
  neutral1: true,
  neutral2: true,
  neutral3: true,
  neutral4: true,
  neutral5: true,
  neutral6: true,
  neutral7: true,
  neutral8: true,
  neutral9: true,
  neutral10: true,
  neutral11: true,
  neutral12: true,
  background1: true,
  background2: true,
  background3: true,
  background4: true,
  background5: true,
  background6: true,
  background7: true,
  background8: true,
  background9: true,
  background10: true,
  background11: true,
  background12: true,
  // Flavor colors
  tomato1: true,
  tomato2: true,
  tomato3: true,
  tomato4: true,
  tomato5: true,
  tomato6: true,
  tomato7: true,
  tomato8: true,
  tomato9: true,
  tomato10: true,
  tomato11: true,
  tomato12: true,
  amber1: true,
  amber2: true,
  amber3: true,
  amber4: true,
  amber5: true,
  amber6: true,
  amber7: true,
  amber8: true,
  amber9: true,
  amber10: true,
  amber11: true,
  amber12: true,
  grass1: true,
  grass2: true,
  grass3: true,
  grass4: true,
  grass5: true,
  grass6: true,
  grass7: true,
  grass8: true,
  grass9: true,
  grass10: true,
  grass11: true,
  grass12: true,
  forest1: true,
  forest2: true,
  forest3: true,
  forest4: true,
  forest5: true,
  forest6: true,
  forest7: true,
  forest8: true,
  forest9: true,
  forest10: true,
  forest11: true,
  forest12: true,
  aqua1: true,
  aqua2: true,
  aqua3: true,
  aqua4: true,
  aqua5: true,
  aqua6: true,
  aqua7: true,
  aqua8: true,
  aqua9: true,
  aqua10: true,
  aqua11: true,
  aqua12: true,
  indigo1: true,
  indigo2: true,
  indigo3: true,
  indigo4: true,
  indigo5: true,
  indigo6: true,
  indigo7: true,
  indigo8: true,
  indigo9: true,
  indigo10: true,
  indigo11: true,
  indigo12: true,
  plum1: true,
  plum2: true,
  plum3: true,
  plum4: true,
  plum5: true,
  plum6: true,
  plum7: true,
  plum8: true,
  plum9: true,
  plum10: true,
  plum11: true,
  plum12: true,
  magenta1: true,
  magenta2: true,
  magenta3: true,
  magenta4: true,
  magenta5: true,
  magenta6: true,
  magenta7: true,
  magenta8: true,
  magenta9: true,
  magenta10: true,
  magenta11: true,
  magenta12: true,
  // Status colors
  error1: true,
  error2: true,
  error3: true,
  error4: true,
  error5: true,
  error6: true,
  error7: true,
  error8: true,
  error9: true,
  error10: true,
  error11: true,
  error12: true,
  info1: true,
  info2: true,
  info3: true,
  info4: true,
  info5: true,
  info6: true,
  info7: true,
  info8: true,
  info9: true,
  info10: true,
  info11: true,
  info12: true,
  success1: true,
  success2: true,
  success3: true,
  success4: true,
  success5: true,
  success6: true,
  success7: true,
  success8: true,
  success9: true,
  success10: true,
  success11: true,
  success12: true,
  warning1: true,
  warning2: true,
  warning3: true,
  warning4: true,
  warning5: true,
  warning6: true,
  warning7: true,
  warning8: true,
  warning9: true,
  warning10: true,
  warning11: true,
  warning12: true,
  // Semantic colors
  surface1: true,
  surface2: true,
  surface3: true,
  inverse: true,
  // Static constants
  white: true,
  black: true,
  transparent: true,
} as const

export const colorText = {
  ...colorCore,
  defaultBody: true,
  defaultHeading: true,
  primaryText1: true,
  primaryText2: true,
  primaryText3: true,
  primaryText4: true,
  primaryText5: true,
  primaryText6: true,
  primaryText7: true,
  primaryText8: true,
  primaryText9: true,
  primaryText10: true,
  primaryText11: true,
  primaryText12: true,
  secondaryText1: true,
  secondaryText2: true,
  secondaryText3: true,
  secondaryText4: true,
  secondaryText5: true,
  secondaryText6: true,
  secondaryText7: true,
  secondaryText8: true,
  secondaryText9: true,
  secondaryText10: true,
  secondaryText11: true,
  secondaryText12: true,
  neutralText1: true,
  neutralText2: true,
  neutralText3: true,
  neutralText4: true,
  neutralText5: true,
  neutralText6: true,
  neutralText7: true,
  neutralText8: true,
  neutralText9: true,
  neutralText10: true,
  neutralText11: true,
  neutralText12: true,
  backgroundText1: true,
  backgroundText2: true,
  backgroundText3: true,
  backgroundText4: true,
  backgroundText5: true,
  backgroundText6: true,
  backgroundText7: true,
  backgroundText8: true,
  backgroundText9: true,
  backgroundText10: true,
  backgroundText11: true,
  backgroundText12: true,
  // Flavor text colors
  tomatoText1: true,
  tomatoText2: true,
  tomatoText3: true,
  tomatoText4: true,
  tomatoText5: true,
  tomatoText6: true,
  tomatoText7: true,
  tomatoText8: true,
  tomatoText9: true,
  tomatoText10: true,
  tomatoText11: true,
  tomatoText12: true,
  amberText1: true,
  amberText2: true,
  amberText3: true,
  amberText4: true,
  amberText5: true,
  amberText6: true,
  amberText7: true,
  amberText8: true,
  amberText9: true,
  amberText10: true,
  amberText11: true,
  amberText12: true,
  grassText1: true,
  grassText2: true,
  grassText3: true,
  grassText4: true,
  grassText5: true,
  grassText6: true,
  grassText7: true,
  grassText8: true,
  grassText9: true,
  grassText10: true,
  grassText11: true,
  grassText12: true,
  forestText1: true,
  forestText2: true,
  forestText3: true,
  forestText4: true,
  forestText5: true,
  forestText6: true,
  forestText7: true,
  forestText8: true,
  forestText9: true,
  forestText10: true,
  forestText11: true,
  forestText12: true,
  aquaText1: true,
  aquaText2: true,
  aquaText3: true,
  aquaText4: true,
  aquaText5: true,
  aquaText6: true,
  aquaText7: true,
  aquaText8: true,
  aquaText9: true,
  aquaText10: true,
  aquaText11: true,
  aquaText12: true,
  indigoText1: true,
  indigoText2: true,
  indigoText3: true,
  indigoText4: true,
  indigoText5: true,
  indigoText6: true,
  indigoText7: true,
  indigoText8: true,
  indigoText9: true,
  indigoText10: true,
  indigoText11: true,
  indigoText12: true,
  plumText1: true,
  plumText2: true,
  plumText3: true,
  plumText4: true,
  plumText5: true,
  plumText6: true,
  plumText7: true,
  plumText8: true,
  plumText9: true,
  plumText10: true,
  plumText11: true,
  plumText12: true,
  magentaText1: true,
  magentaText2: true,
  magentaText3: true,
  magentaText4: true,
  magentaText5: true,
  magentaText6: true,
  magentaText7: true,
  magentaText8: true,
  magentaText9: true,
  magentaText10: true,
  magentaText11: true,
  magentaText12: true,
  // Status text colors
  errorText1: true,
  errorText2: true,
  errorText3: true,
  errorText4: true,
  errorText5: true,
  errorText6: true,
  errorText7: true,
  errorText8: true,
  errorText9: true,
  errorText10: true,
  errorText11: true,
  errorText12: true,
  infoText1: true,
  infoText2: true,
  infoText3: true,
  infoText4: true,
  infoText5: true,
  infoText6: true,
  infoText7: true,
  infoText8: true,
  infoText9: true,
  infoText10: true,
  infoText11: true,
  infoText12: true,
  successText1: true,
  successText2: true,
  successText3: true,
  successText4: true,
  successText5: true,
  successText6: true,
  successText7: true,
  successText8: true,
  successText9: true,
  successText10: true,
  successText11: true,
  successText12: true,
  warningText1: true,
  warningText2: true,
  warningText3: true,
  warningText4: true,
  warningText5: true,
  warningText6: true,
  warningText7: true,
  warningText8: true,
  warningText9: true,
  warningText10: true,
  warningText11: true,
  warningText12: true,
  // Semantic colors
  shadowColor: true,
  surface1: true,
  surface2: true,
  surface3: true,
  inverse: true,
  white: true,
  black: true,
  transparent: true,
} as const
