// Infrastructure
export { Provider } from './provider'
export type { ProviderProps } from './provider'

// Layer 0 — Design Tokens
export {
  tokens,
  size,
  space,
  radius,
  color,
  zIndex,
  borderWidth,
  semanticColorMap,
  buildThemes,
  lightPalette,
  darkPalette,
  accentPalettes,
  lightShadows,
  darkShadows,
  createBrandConfig,
  defaultBrand,
  funBrand,
  poshBrand,
  shadcnBrand,
  media,
} from '../packages/design-tokens'
export type {
  BrandDefinition,
  BrandFontConfig,
  BorderConfig,
  OutlineConfig,
  AnimationConfig,
  TypographyConfig,
  TokenOverrides,
  FontOverrides,
  ShadowToken,
  ShadowScale,
} from '../packages/design-tokens'

// Layer 1 — Primitives
export {
  Box,
  Stack,
  VStack,
  HStack,
  Text,
  Heading,
  Icon,
  Divider,
  Spacer,
  Portal,
  Label,
  VisuallyHidden,
  Badge,
  Skeleton,
  Separator,
  AspectRatio,
  Spinner,
  Kbd,
} from '../packages/primitives'
export type {
  BoxProps,
  StackProps,
  VStackProps,
  HStackProps,
  TextProps,
  HeadingProps,
  IconProps,
  IconFC,
  DividerProps,
  SpacerProps,
  PortalProps,
  LabelProps,
  VisuallyHiddenProps,
  BadgeProps,
  SkeletonProps,
  SeparatorProps,
  AspectRatioProps,
  SpinnerProps,
  KbdProps,
} from '../packages/primitives'

// Layer 2 — Styled Components
export {
  Button,
  Input,
  InputGroup,
  Card,
  Chart,
  useChartContext,
  ChartTooltip,
  ChartLegend,
  ChartDataTable,
  AreaChart,
  BarChart,
  LineChart,
  PieChart,
  RadarChart,
  RadialChart,
  Dialog,
  Direction,
  DirectionProvider,
  useDirection,
  Tabs,
  Checkbox,
  Switch,
  RadioGroup,
  Alert,
  Textarea,
  Avatar,
  Progress,
  Slider,
  Toggle,
  ToggleGroup,
  Tooltip,
  TooltipProvider,
  Select,
  Accordion,
  Collapsible,
  AlertDialog,
  Table,
  DataTable,
  Breadcrumb,
  Form,
  Pagination,
  DatePicker,
  DateRangePicker,
  ScrollArea,
  HoverCard,
  NativeSelect,
  InputOTP,
  Item,
  ButtonGroup,
  Drawer,
  H1,
  H2,
  H3,
  H4,
  P,
  Lead,
  Large,
  Small,
  Muted,
  Blockquote,
  InlineCode,
  List,
  ListItem,
  Calendar,
  Combobox,
  Command,
  ContextMenu,
  DropdownMenu,
  Menubar,
  NavigationMenu,
  Carousel,
  Resizable,
  Sidebar,
  Loader,
  Popover,
  Sheet,
  Field,
  Empty,
  Toast,
  useToastController,
  useToastState,
  toast,
  ImperativeToastViewport,
  useImperativeToasts,
} from '../packages/components'
export type {
  ButtonProps,
  InputProps,
  InputGroupProps,
  InputGroupAddonProps,
  InputGroupElementProps,
  InputGroupInputProps,
  CardProps,
  ChartContainerProps,
  ChartTooltipProps,
  ChartLegendProps,
  ChartDataTableProps,
  ChartConfig,
  ChartConfigEntry,
  ChartDataPoint,
  TooltipVariant,
  TooltipIndicator,
  LegendLayout,
  AreaChartProps,
  AreaChartVariant,
  BarChartProps,
  BarChartVariant,
  LineChartProps,
  LineChartVariant,
  PieChartProps,
  PieChartVariant,
  RadarChartProps,
  RadarChartVariant,
  RadialChartProps,
  RadialChartVariant,
  SwitchProps,
  RadioGroupRootProps,
  RadioGroupItemProps,
  AlertProps,
  TextareaProps,
  AvatarProps,
  ProgressProps,
  SliderProps,
  ToggleProps,
  ToggleGroupProps,
  ToggleGroupItemProps,
  TooltipProps,
  TooltipProviderProps,
  SelectProps,
  SelectItemProps,
  AccordionRootProps,
  AccordionItemProps,
  AccordionTriggerProps,
  AccordionContentProps,
  CollapsibleRootProps,
  CollapsibleTriggerProps,
  CollapsibleContentProps,
  BreadcrumbProps,
  FormRootProps,
  FormFieldProps,
  PaginationProps,
  DatePickerProps,
  DateRangePickerProps,
  ScrollAreaRootProps,
  ScrollAreaViewportProps,
  HoverCardRootProps,
  HoverCardContentProps,
  NativeSelectRootProps,
  NativeSelectOptionProps,
  DirectionProviderProps,
  InputOTPRootProps,
  InputOTPSlotProps,
  ItemProps,
  ItemLeadingProps,
  ItemContentProps,
  ItemTitleProps,
  ItemDescriptionProps,
  ItemTrailingProps,
  ButtonGroupRootProps,
  DrawerRootProps,
  DrawerContentProps,
  CalendarRootProps,
  CalendarDayProps,
  ComboboxRootProps,
  ComboboxOption,
  ComboboxItemProps,
  CommandRootProps,
  CommandItemProps,
  CommandGroupProps,
  ContextMenuRootProps,
  ContextMenuItemProps,
  ContextMenuCheckboxItemProps,
  DropdownMenuRootProps,
  DropdownMenuItemProps,
  DropdownMenuCheckboxItemProps,
  MenubarRootProps,
  MenubarMenuProps,
  MenubarItemProps,
  NavigationMenuRootProps,
  NavigationMenuItemProps,
  NavigationMenuLinkProps,
  CarouselRootProps,
  CarouselItemProps,
  ResizablePanelGroupProps,
  ResizablePanelProps,
  ResizableHandleProps,
  SidebarRootProps,
  SidebarGroupProps,
  SidebarMenuItemProps,
  LoaderProps,
  PopoverRootProps,
  SheetRootProps,
  FieldRootProps,
  FieldLabelProps,
  FieldControlProps,
  FieldDescriptionProps,
  FieldErrorProps,
  EmptyRootProps,
  EmptyTitleProps,
  EmptyDescriptionProps,
  EmptyMediaProps,
  EmptyActionProps,
  ToastRootProps,
  ToastViewportProps,
  ToastProviderProps,
  ToastData,
  PromiseToastData,
  DataTableProps,
  ColumnDef,
  SortingState,
  ColumnFiltersState,
  VisibilityState,
  PaginationState,
} from '../packages/components'

// Hooks
export {
  useControllableState,
  useFocusTrap,
  useKeyboardNavigation,
} from '../packages/hooks'

// Utils
export {
  mergeRefs,
  composeEventHandlers,
  cn,
  FontLoader,
  getGoogleFontsUrl,
  useFontLoader,
  isSystemFont,
  extractFamiliesFromConfig,
  buildFaceMapsFromConfig,
} from '../packages/utils'
export type { FontLoaderProps, FontLoadState } from '../packages/utils'

// Icons (Remix Icon)
export { DynamicIcon } from '../packages/icons/Icon'
export type { DynamicIconProps } from '../packages/icons/Icon'
export { createIcon } from '../packages/icons/createIcon'
export type { IconFC as RemixIconFC } from '../packages/icons/createIcon'
